CREATE TABLE /*_*/continuum_lexicon (
  clx_id                INT UNSIGNED NOT NULL AUTO_INCREMENT,
  clx_language          VARBINARY(64) NOT NULL,
  clx_language_id       INT UNSIGNED DEFAULT NULL,
  clx_lemma             VARBINARY(255) NOT NULL,
  clx_romanized         VARBINARY(255) DEFAULT NULL,
  clx_ipa               VARBINARY(255) DEFAULT NULL,
  clx_pos               VARBINARY(64) DEFAULT NULL,
  clx_gloss             VARBINARY(255) DEFAULT NULL,
  clx_definition        MEDIUMBLOB DEFAULT NULL,
  clx_etymology         MEDIUMBLOB DEFAULT NULL,
  clx_parent_id         INT UNSIGNED DEFAULT NULL,
  clx_evolution_profile VARBINARY(255) DEFAULT NULL,
  clx_notes             MEDIUMBLOB DEFAULT NULL,
  clx_source_page_id    INT UNSIGNED DEFAULT NULL,
  clx_created_at        BINARY(14) NOT NULL,
  clx_updated_at        BINARY(14) NOT NULL,
  PRIMARY KEY (clx_id),
  KEY clx_language (clx_language),
  KEY clx_language_id (clx_language_id),
  KEY clx_pos (clx_pos),
  KEY clx_lemma (clx_lemma),
  KEY clx_parent_id (clx_parent_id),
  KEY clx_source_page_id (clx_source_page_id)
) /*$wgDBTableOptions*/;
